risk/urls.py
from django.urls import path

from . import views

app_name = "risk"
urlpatterns = [
    path(
        "dashboard",
        views.LoginRequiredTemplateView.as_view(template_name="risk/dashboard.html"),
        name="dashboard",
    ),
    path("dashboard_htmx", views.DashboardHtmxView.as_view(), name="dashboard_htmx"),
    path(
        "risk_scenario",
        views.LoginRequiredTemplateView.as_view(
            template_name="risk/risk_scenario.html"
        ),
        name="risk_scenario",
    ),
    path(
        "risk_scenario_htmx",
        views.RiskScenarioHtmxView.as_view(),
        name="risk_scenario_htmx",
    ),
    path(
        "risk_table",
        views.LoginRequiredTemplateView.as_view(template_name="risk/risk_table.html"),
        name="risk_table",
    ),
    path("risk_table_htmx", views.RiskTableHtmxView.as_view(), name="risk_table_htmx"),
    path("project_htmx/<int:pk>", views.ProjectHtmxView.as_view(), name="project_htmx"),
    path("risk_htmx/<int:pk>", views.RiskHtmxView.as_view(), name="risk_htmx"),
    path("risk_delete/<int:pk>", views.RiskDeleteView.as_view(), name="risk_delete"),
]

risk/models/project.py
from django.contrib.auth.models import User
from django.db import models

from .project_manager import ProjectManager


class Project(models.Model):
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=128)

    objects = ProjectManager()

    def __str__(self):
        return f"{self.name}"

risk/models/project_manager.py
from django.db import models
from django.db.models import Count, Q
from django.db.models.query import QuerySet


class ProjectManager(models.Manager):
    def get_summary(self) -> QuerySet:
        """
        Get summary of projects
            - sum of Unresolved High Severity
            - sum of Unresolved Risk
            - sum of Resolved Risk
            - sum of All Risk
        :return: Project QuerySet
        """
        unresolved_high_severity = Count(
            "risk",
            filter=~Q(risk__status="fully_mitigated")
            & Q(risk__scenario__severity="high"),
        )
        unresolved_risk = Count("risk", filter=~Q(risk__status="fully_mitigated"))
        resolved_risk = Count("risk", filter=Q(risk__status="fully_mitigated"))
        all_risk = Count("risk")
        return (
            self.annotate(unresolved_high_severity=unresolved_high_severity)
            .annotate(unresolved_risk=unresolved_risk)
            .annotate(resolved_risk=resolved_risk)
            .annotate(all_risk=all_risk)
        )

risk/models/risk.py
from django.db import models


class Risk(models.Model):
    STATUS_CHOICES = (
        ("not_mitigated", "NOT MITIGATED"),
        ("partially_mitigated", "PARTIALLY MITIGATED"),
        ("fully_mitigated", "FULLY MITIGATED"),
    )

    scenario = models.ForeignKey("risk.RiskScenario", on_delete=models.CASCADE)
    project = models.ForeignKey(
        "risk.Project", on_delete=models.CASCADE, related_name="risk"
    )
    status = models.CharField(max_length=32, choices=STATUS_CHOICES)

    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.project.name} - {self.scenario.name} - {self.status}"

risk/models/risk_scenario.py
from django.contrib.auth.models import User
from django.db import models


class RiskScenario(models.Model):
    LEVEL_CHOICES = (("high", "HIGH"), ("medium", "MEDIUM"), ("low", "LOW"))

    TARGET_CHOICES = (
        ("dataflow", "DATAFLOW"),
        ("server", "SERVER"),
        ("process", "PROCESS"),
        ("datastore", "DATASTORE"),
    )

    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    name = models.CharField(max_length=128)
    description = models.TextField()
    mitigation_strategy = models.TextField()
    severity = models.CharField(max_length=32, choices=LEVEL_CHOICES)
    likelihood_of_attack = models.CharField(max_length=32, choices=LEVEL_CHOICES)
    target = models.CharField(max_length=32, choices=TARGET_CHOICES)

    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name}"

risk/forms/risk_form.py
from django import forms

from risk.models import Project, Risk


class RiskForm(forms.ModelForm):
    class Meta:
        model = Risk
        fields = ["project"]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

        self.fields["project"].queryset = Project.objects.filter(owner=user)

risk/views/dashboard_htmx_view.py
from collections import Counter

import plotly.graph_objects as go
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from risk.models import Project


class DashboardHtmxView(LoginRequiredMixin, TemplateView):
    """
    View for displaying Dashboard

    Permission "risk.change_risk" and "risk.view_risk"
        - View Project Manager dashboard
    Permission "risk.view_risk
        - View Risk Consultant dashboard
    """

    template_name = "risk/htmx/dashboard/no_permission_dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Project Manager Role
        if self.request.user.has_perm(
            "risk.change_risk"
        ) and self.request.user.has_perm("risk.view_risk"):
            self.template_name = "risk/htmx/dashboard/project_manager_dashboard.html"
            project_objects = (
                Project.objects.get_summary()
                .filter(owner=self.request.user)
                .prefetch_related("risk")
                .prefetch_related("risk__scenario")
            )
        # Risk Consultant Role
        elif self.request.user.has_perm("risk.view_risk"):
            self.template_name = "risk/htmx/dashboard/risk_consultant_dashboard.html"
            project_objects = (
                Project.objects.get_summary()
                .prefetch_related("risk")
                .prefetch_related("risk__scenario")
                .order_by("all_risk")
            )
            risk_scenario = [
                risk.scenario.name
                for project in project_objects
                for risk in project.risk.all()
            ]
            risk_scenario_counts = Counter(risk_scenario)

            risk_scenario_heatmap = [
                (
                    risk.scenario.name,
                    risk.scenario.created_datetime.strftime("%Y-%m-%d"),
                )
                for project in project_objects
                for risk in project.risk.all()
            ]
            risk_scenario_heatmap_counts = Counter(risk_scenario_heatmap)
            risk_scenario_heatmap_labels = list(risk_scenario_heatmap_counts.keys())
            risk_scenario_heatmap_values = list(risk_scenario_heatmap_counts.values())

            # Create a Heatmap
            fig_heatmap = go.Figure(
                data=go.Heatmap(
                    z=risk_scenario_heatmap_values,
                    x=[i[1] for i in risk_scenario_heatmap_labels],
                    y=[i[0] for i in risk_scenario_heatmap_labels],
                    colorscale="Viridis",
                )
            )

            # Create a Horizontal Bar chart
            fig_hor = go.Figure(
                data=[
                    go.Bar(
                        y=[project.name for project in project_objects],
                        x=[project.all_risk for project in project_objects],
                        orientation="h",
                    )
                ]
            )

            # Create a Pie chart
            fig = go.Figure(
                data=[
                    go.Pie(
                        labels=list(risk_scenario_counts.keys()),
                        values=list(risk_scenario_counts.values()),
                        hole=0.3,
                    )
                ]
            )

            context["risk_scenario_pie_chart"] = fig.to_html()
            context["top_project_risk_bar_chart"] = fig_hor.to_html()
            context["risk_heat_map"] = fig_heatmap.to_html()
            context["risk_scenario_counts"] = dict(risk_scenario_counts)

        else:
            return context

        context["total_unresolved_high_severity_risk"] = sum(
            project.unresolved_high_severity for project in project_objects
        )
        context["total_unresolved_risk"] = sum(
            project.unresolved_risk for project in project_objects
        )

        return context

risk/views/login_required_template_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class LoginRequiredTemplateView(LoginRequiredMixin, TemplateView):
    """
    View for login required templates
    """

    pass

risk/views/project_htmx_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, UpdateView

from risk.models import Project, Risk


class ProjectHtmxView(LoginRequiredMixin, DetailView, UpdateView):
    """
    View to generate Project Detail modal from Risk Table
    """

    template_name = "risk/htmx/project_htmx.html"
    queryset = (
        Project.objects.prefetch_related("risk")
        .prefetch_related("risk__scenario")
        .all()
    )
    fields = ["status"]
    model = Risk

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["mitigated_risks"] = self.get_object().risk.filter(
            status="fully_mitigated"
        )
        context["not_mitigated_risks"] = self.get_object().risk.exclude(
            status="fully_mitigated"
        )

        return context

risk/views/risk_delete_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DeleteView

from risk.models import Risk


class RiskDeleteView(LoginRequiredMixin, DeleteView):
    """
    View to delete Risk

    Permission "risk.change_risk"
        - POST to delete Risk
    """

    model = Risk
    success_url = reverse_lazy("risk:risk_table")

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.has_perm("risk.change_risk"):
            return super().dispatch(request, *args, **kwargs)
        else:
            return self.handle_no_permission()

risk/views/risk_htmx_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import UpdateView

from risk.models import Risk


class RiskHtmxView(LoginRequiredMixin, UpdateView):
    """
    View to update Risk

    Permission "risk.change_risk"
        - POST to update Risk
    """

    fields = ["status"]
    model = Risk
    success_url = reverse_lazy("risk:risk_table")

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.has_perm("risk.change_risk"):
            return super().dispatch(request, *args, **kwargs)
        else:
            return self.handle_no_permission()

risk/views/risk_scenario_htmx_view.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView

from risk.forms import RiskForm
from risk.models import Risk, RiskScenario


class RiskScenarioHtmxView(LoginRequiredMixin, ListView, FormView):
    """
    View for displaying a table of Risk Scenario and handle creation of Risk.

    Permission "risk.change_risk"
        - POST to create new risk
    """

    template_name = "risk/htmx/risk_scenario_htmx.html"
    model = RiskScenario
    form_class = RiskForm
    success_url = reverse_lazy("risk:risk_scenario")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def post(self, request, *args, **kwargs):
        if self.request.user.has_perm("risk.change_risk"):
            return super().post(request, *args, **kwargs)
        else:
            return self.handle_no_permission()

    def form_valid(self, form):
        risk_scenario_object = get_object_or_404(
            RiskScenario, pk=self.request.POST.get("scenario")
        )
        if Risk.objects.filter(
            scenario=risk_scenario_object, project=form.cleaned_data["project"]
        ).exists():
            messages.error(
                self.request,
                f"{risk_scenario_object.name} already exists for {form.cleaned_data['project']}",
                extra_tags="danger",
            )
            return HttpResponseRedirect(self.get_success_url())

        new_risk = form.save(commit=False)
        new_risk.scenario = risk_scenario_object
        new_risk.status = "not_mitigated"
        new_risk.save()
        messages.info(
            self.request,
            f"{risk_scenario_object.name} created successfully for {form.cleaned_data['project']}",
        )

        return HttpResponseRedirect(self.get_success_url())

risk/views/risk_table_htmx_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from risk.models import Project


class RiskTableHtmxView(LoginRequiredMixin, ListView):
    """
    View for displaying a table of Project summaries

    Permission "risk.view_project"
        - View all projects
    w/o Permission "risk.view_project"
        - View only projects owned by user
    """

    template_name = "risk/htmx/risk_table_htmx.html"
    queryset = Project.objects.get_summary()

    def get_queryset(self, **kwargs):
        if not self.request.user.has_perm("risk.view_project"):
            self.queryset = self.queryset.filter(owner=self.request.user)

        return super().get_queryset(**kwargs)

risk/templates/risk/htmx/project_htmx.html
{% load template_tag %}

<div class="modal-header">
  <h5 class="modal-title" id="modalCenterTitle">{{ object.name }} Risks</h5>
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="modal"
    aria-label="Close"></button>
</div>
<div class="modal-body">
  <div class="row">
    <div class="col mb-3">
      <ul class="nav nav-pills mb-3" role="tablist">
        <li class="nav-item">
          <button
            type="button"
            class="nav-link active"
            role="tab"
            data-bs-toggle="tab"
            data-bs-target="#navs-not-mitigated-risks"
            aria-controls="navs-not-mitigated-risks"
            aria-selected="true">
            Not Mitigated Risks
            {% if not_mitigated_risks|length > 0 %}
            <span class="badge rounded-pill badge-center h-px-20 w-px-20 bg-danger ms-1">{{ not_mitigated_risks|length }}</span>
            {% endif %}
          </button>
        </li>
        <li class="nav-item">
          <button
            type="button"
            class="nav-link"
            role="tab"
            data-bs-toggle="tab"
            data-bs-target="#navs-mitigated-risks"
            aria-controls="navs-mitigated-risks"
            aria-selected="false">
            Mitigated Risks
            <span class="badge rounded-pill badge-center h-px-20 w-px-20 bg-info ms-1">{{ mitigated_risks|length }}</span>
          </button>
        </li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane fade show active" id="navs-not-mitigated-risks" role="tabpanel">
          <table id="risk_detail_datatable" class="table table-striped" style="width:100%">
            <thead>
              <tr>
                <th>Name</th>
                <th>Mitigation Strategy</th>
                <th>Severity</th>
                <th>Likelihood Of Attack</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {% for risk_object in not_mitigated_risks %}
              <tr>
                <td>
                  {{ risk_object.scenario.name }}
                  <i class="bx bx-info-circle bx-sm me-3" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ risk_object.scenario.description }}"></i>
                </td>
                <td>{{ risk_object.scenario.mitigation_strategy }}</td>
                <td>
                  <span class="badge rounded-pill
                  {% if risk_object.scenario.severity == 'high' %}bg-danger
                  {% elif risk_object.scenario.severity == 'medium' %}bg-warning
                  {% elif risk_object.scenario.severity == 'low' %}bg-info
                  {% endif %}">{{ risk_object.scenario.severity }}</span>
                </td>
                <td>
                  <span class="badge rounded-pill
                  {% if risk_object.scenario.likelihood_of_attack == 'high' %}bg-danger
                  {% elif risk_object.scenario.likelihood_of_attack == 'medium' %}bg-warning
                  {% elif risk_object.scenario.likelihood_of_attack == 'low' %}bg-info
                  {% endif %}">{{ risk_object.scenario.likelihood_of_attack }}</span>
                </td>
                <td>
                  {{ risk_object.get_status_display }}
                  {% if perms.risk.change_risk %}
                  <form method="post" action="{% url 'risk:risk_htmx' risk_object.id %}">
                    {% csrf_token %}
                    {% for field in form %}
                    {{ field|add_css:'form-select mb-3' }}
                    {% endfor %}
                    <button type="submit" value="Update" class="btn btn-primary mb-3">Update</button>
                  </form>
                  <form method="post" action="{% url 'risk:risk_delete' risk_object.id %}">
                    {% csrf_token %}
                    <button type="submit" value="Delete" class="btn btn-danger">Delete</button>
                  </form>
                  {% endif %}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="tab-pane fade" id="navs-mitigated-risks" role="tabpanel">
          <table id="mitigated_risk_detail_datatable" class="table table-striped" style="width:100%">
            <thead>
              <tr>
                <th>Name</th>
                <th>Mitigation Strategy</th>
                <th>Severity</th>
                <th>Likelihood Of Attack</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {% for risk_object in mitigated_risks %}
              <tr>
                <td>
                  {{ risk_object.scenario.name }}
                  <i class="bx bx-info-circle bx-sm me-3" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ risk_object.scenario.description }}"></i>
                </td>
                <td>{{ risk_object.scenario.mitigation_strategy }}</td>
                <td>
                  <span class="badge rounded-pill
                  {% if risk_object.scenario.severity == 'high' %}bg-danger
                  {% elif risk_object.scenario.severity == 'medium' %}bg-warning
                  {% elif risk_object.scenario.severity == 'low' %}bg-info
                  {% endif %}">{{ risk_object.scenario.severity }}</span>
                </td>
                <td>
                  <span class="badge rounded-pill
                  {% if risk_object.scenario.likelihood_of_attack == 'high' %}bg-danger
                  {% elif risk_object.scenario.likelihood_of_attack == 'medium' %}bg-warning
                  {% elif risk_object.scenario.likelihood_of_attack == 'low' %}bg-info
                  {% endif %}">{{ risk_object.scenario.likelihood_of_attack }}</span>
                </td>
                <td>
                  {{ risk_object.get_status_display }}
                  {% if perms.risk.change_risk %}
                  <form method="post" action="{% url 'risk:risk_htmx' risk_object.id %}">
                    {% csrf_token %}
                    {% for field in form %}
                    {{ field|add_css:'form-select mb-3' }}
                    {% endfor %}
                    <button type="submit" value="Update" class="btn btn-primary mb-3">Update</button>
                  </form>
                  <form method="post" action="{% url 'risk:risk_delete' risk_object.id %}">
                    {% csrf_token %}
                    <button type="submit" value="Delete" class="btn btn-danger">Delete</button>
                  </form>
                  {% endif %}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
    $(document).ready(function() {
      new DataTable('#risk_detail_datatable');
      new DataTable('#mitigated_risk_detail_datatable');
      const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
      const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    })
</script>

risk/templates/risk/htmx/risk_scenario_htmx.html
{% load template_tag %}

<table id="risk_scenario_datatable" class="table table-striped" style="width:100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Mitigation Strategy</th>
      <th>Severity</th>
      <th>Likelihood of attack</th>
      {% if perms.risk.change_risk %}
      <th>Action</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr>
      <td>{{ object.name }}</td>
      <td>{{ object.description }}</td>
      <td>{{ object.mitigation_strategy }}</td>
      <td>
        <span class="badge rounded-pill
        {% if object.severity == 'high' %}bg-danger
        {% elif object.severity == 'medium' %}bg-warning
        {% elif object.severity == 'low' %}bg-info
        {% endif %}">{{ object.severity }}</span>
      </td>
      <td>
        <span class="badge rounded-pill
        {% if object.likelihood_of_attack == 'high' %}bg-danger
        {% elif object.likelihood_of_attack == 'medium' %}bg-warning
        {% elif object.likelihood_of_attack == 'low' %}bg-info
        {% endif %}">{{ object.likelihood_of_attack }}</span>
      </td>
      {% if perms.risk.change_risk %}
      <td>
        <form method="post" action="{% url 'risk:risk_scenario_htmx'%}">
          {% csrf_token %}
          {% for field in form %}
          {{ field|add_css:'form-select mb-3' }}
          {% endfor %}
          <input type="hidden" id="id_scenario" name="scenario" value="{{ object.id }}">
          <button type="submit" class="btn btn-primary">Add to project</button>
        </form>
      </td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>

<script>
    $(document).ready(function() {
      new DataTable('#risk_scenario_datatable');
    })
</script>

risk/templates/risk/htmx/risk_table_htmx.html
<table id="risk_scenario_datatable" class="table table-striped" style="width:100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner</th>
      <th>Unresolved High Severity Risk</th>
      <th>Unresolved Risks</th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr
      class="clickable-row"
      style="cursor: pointer;"
      data-bs-toggle="modal"
      data-bs-target="#riskDetailModal"
      hx-target="#modalContent"
      hx-get="{% url 'risk:project_htmx' object.id %}?"
    >
      <td>{{ object.name }}</td>
      <td><i class="bx bx-user-circle bx-sm me-3"></i>{{ object.owner.username }}</td>
      <td>
        {% if object.unresolved_high_severity > 0 %}
        <span class="badge rounded-pill bg-danger">{{ object.unresolved_high_severity }}</span>
        {% else %}
        <span class="badge rounded-pill bg-success">{{ object.unresolved_high_severity }}</span>
        {% endif %}
      </td>
      <td>{{ object.unresolved_risk }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="riskDetailModal" tabindex="-1"  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-xl">
    <div class="modal-content" id="modalContent"></div>
  </div>
</div>