risk/urls.py
from django.urls import path

from . import views

app_name = "risk"
urlpatterns = [
    path(
        "dashboard",
        views.LoginRequiredTemplateView.as_view(template_name="risk/dashboard.html"),
        name="dashboard",
    ),
    path("dashboard_htmx", views.DashboardHtmxView.as_view(), name="dashboard_htmx"),
    path(
        "risk_scenario",
        views.LoginRequiredTemplateView.as_view(
            template_name="risk/risk_scenario.html"
        ),
        name="risk_scenario",
    ),
    path(
        "risk_scenario_htmx",
        views.RiskScenarioHtmxView.as_view(),
        name="risk_scenario_htmx",
    ),
    path(
        "risk_table",
        views.LoginRequiredTemplateView.as_view(template_name="risk/risk_table.html"),
        name="risk_table",
    ),
    path("risk_table_htmx", views.RiskTableHtmxView.as_view(), name="risk_table_htmx"),
    path("project_htmx/<int:pk>", views.ProjectHtmxView.as_view(), name="project_htmx"),
    path("risk_htmx/<int:pk>", views.RiskHtmxView.as_view(), name="risk_htmx"),
    path("risk_delete/<int:pk>", views.RiskDeleteView.as_view(), name="risk_delete"),
]

risk/models/project.py
from django.contrib.auth.models import User
from django.db import models

from .project_manager import ProjectManager


class Project(models.Model):
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=128)

    objects = ProjectManager()

    def __str__(self):
        return f"{self.name}"

risk/models/project_manager.py
from django.db import models
from django.db.models import Count, Q
from django.db.models.query import QuerySet


class ProjectManager(models.Manager):
    def get_summary(self) -> QuerySet:
        """
        Get summary of projects
            - sum of Unresolved High Severity
            - sum of Unresolved Risk
            - sum of Resolved Risk
            - sum of All Risk
        :return: Project QuerySet
        """
        unresolved_high_severity = Count(
            "risk",
            filter=~Q(risk__status="fully_mitigated")
            & Q(risk__scenario__severity="high"),
        )
        unresolved_risk = Count("risk", filter=~Q(risk__status="fully_mitigated"))
        resolved_risk = Count("risk", filter=Q(risk__status="fully_mitigated"))
        all_risk = Count("risk")
        return (
            self.annotate(unresolved_high_severity=unresolved_high_severity)
            .annotate(unresolved_risk=unresolved_risk)
            .annotate(resolved_risk=resolved_risk)
            .annotate(all_risk=all_risk)
        )

risk/models/risk.py
from django.db import models


class Risk(models.Model):
    STATUS_CHOICES = (
        ("not_mitigated", "NOT MITIGATED"),
        ("partially_mitigated", "PARTIALLY MITIGATED"),
        ("fully_mitigated", "FULLY MITIGATED"),
    )

    scenario = models.ForeignKey("risk.RiskScenario", on_delete=models.CASCADE)
    project = models.ForeignKey(
        "risk.Project", on_delete=models.CASCADE, related_name="risk"
    )
    status = models.CharField(max_length=32, choices=STATUS_CHOICES)

    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.project.name} - {self.scenario.name} - {self.status}"

risk/models/risk_scenario.py
from django.contrib.auth.models import User
from django.db import models


class RiskScenario(models.Model):
    LEVEL_CHOICES = (("high", "HIGH"), ("medium", "MEDIUM"), ("low", "LOW"))

    TARGET_CHOICES = (
        ("dataflow", "DATAFLOW"),
        ("server", "SERVER"),
        ("process", "PROCESS"),
        ("datastore", "DATASTORE"),
    )

    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    name = models.CharField(max_length=128)
    description = models.TextField()
    mitigation_strategy = models.TextField()
    severity = models.CharField(max_length=32, choices=LEVEL_CHOICES)
    likelihood_of_attack = models.CharField(max_length=32, choices=LEVEL_CHOICES)
    target = models.CharField(max_length=32, choices=TARGET_CHOICES)

    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name}"

risk/forms/risk_form.py
from django import forms

from risk.models import Project, Risk


class RiskForm(forms.ModelForm):
    class Meta:
        model = Risk
        fields = ["project"]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

        self.fields["project"].queryset = Project.objects.filter(owner=user)

risk/views/dashboard_htmx_view.py
from collections import Counter

import plotly.graph_objects as go
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from risk.models import Project


class DashboardHtmxView(LoginRequiredMixin, TemplateView):
    """
    View for displaying Dashboard

    Permission "risk.change_risk" and "risk.view_risk"
        - View Project Manager dashboard
    Permission "risk.view_risk
        - View Risk Consultant dashboard
    """

    template_name = "risk/htmx/dashboard/no_permission_dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Project Manager Role
        if self.request.user.has_perm(
            "risk.change_risk"
        ) and self.request.user.has_perm("risk.view_risk"):
            self.template_name = "risk/htmx/dashboard/project_manager_dashboard.html"
            project_objects = (
                Project.objects.get_summary()
                .filter(owner=self.request.user)
                .prefetch_related("risk")
                .prefetch_related("risk__scenario")
            )
        # Risk Consultant Role
        elif self.request.user.has_perm("risk.view_risk"):
            self.template_name = "risk/htmx/dashboard/risk_consultant_dashboard.html"
            project_objects = (
                Project.objects.get_summary()
                .prefetch_related("risk")
                .prefetch_related("risk__scenario")
                .order_by("all_risk")
            )
            risk_scenario = [
                risk.scenario.name
                for project in project_objects
                for risk in project.risk.all()
            ]
            risk_scenario_counts = Counter(risk_scenario)

            risk_scenario_heatmap = [
                (
                    risk.scenario.name,
                    risk.scenario.created_datetime.strftime("%Y-%m-%d"),
                )
                for project in project_objects
                for risk in project.risk.all()
            ]
            risk_scenario_heatmap_counts = Counter(risk_scenario_heatmap)
            risk_scenario_heatmap_labels = list(risk_scenario_heatmap_counts.keys())
            risk_scenario_heatmap_values = list(risk_scenario_heatmap_counts.values())

            # Create a Heatmap
            fig_heatmap = go.Figure(
                data=go.Heatmap(
                    z=risk_scenario_heatmap_values,
                    x=[i[1] for i in risk_scenario_heatmap_labels],
                    y=[i[0] for i in risk_scenario_heatmap_labels],
                    colorscale="Viridis",
                )
            )

            # Create a Horizontal Bar chart
            fig_hor = go.Figure(
                data=[
                    go.Bar(
                        y=[project.name for project in project_objects],
                        x=[project.all_risk for project in project_objects],
                        orientation="h",
                    )
                ]
            )

            # Create a Pie chart
            fig = go.Figure(
                data=[
                    go.Pie(
                        labels=list(risk_scenario_counts.keys()),
                        values=list(risk_scenario_counts.values()),
                        hole=0.3,
                    )
                ]
            )

            context["risk_scenario_pie_chart"] = fig.to_html()
            context["top_project_risk_bar_chart"] = fig_hor.to_html()
            context["risk_heat_map"] = fig_heatmap.to_html()
            context["risk_scenario_counts"] = dict(risk_scenario_counts)

        else:
            return context

        context["total_unresolved_high_severity_risk"] = sum(
            project.unresolved_high_severity for project in project_objects
        )
        context["total_unresolved_risk"] = sum(
            project.unresolved_risk for project in project_objects
        )

        return context

risk/views/login_required_template_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class LoginRequiredTemplateView(LoginRequiredMixin, TemplateView):
    """
    View for login required templates
    """

    pass

risk/views/project_htmx_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, UpdateView

from risk.models import Project, Risk


class ProjectHtmxView(LoginRequiredMixin, DetailView, UpdateView):
    """
    View to generate Project Detail modal from Risk Table
    """

    template_name = "risk/htmx/project_htmx.html"
    queryset = (
        Project.objects.prefetch_related("risk")
        .prefetch_related("risk__scenario")
        .all()
    )
    fields = ["status"]
    model = Risk

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["mitigated_risks"] = self.get_object().risk.filter(
            status="fully_mitigated"
        )
        context["not_mitigated_risks"] = self.get_object().risk.exclude(
            status="fully_mitigated"
        )

        return context

risk/views/risk_delete_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DeleteView

from risk.models import Risk


class RiskDeleteView(LoginRequiredMixin, DeleteView):
    """
    View to delete Risk

    Permission "risk.change_risk"
        - POST to delete Risk
    """

    model = Risk
    success_url = reverse_lazy("risk:risk_table")

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.has_perm("risk.change_risk"):
            return super().dispatch(request, *args, **kwargs)
        else:
            return self.handle_no_permission()

risk/views/risk_htmx_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import UpdateView

from risk.models import Risk


class RiskHtmxView(LoginRequiredMixin, UpdateView):
    """
    View to update Risk

    Permission "risk.change_risk"
        - POST to update Risk
    """

    fields = ["status"]
    model = Risk
    success_url = reverse_lazy("risk:risk_table")

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.has_perm("risk.change_risk"):
            return super().dispatch(request, *args, **kwargs)
        else:
            return self.handle_no_permission()

risk/views/risk_scenario_htmx_view.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView

from risk.forms import RiskForm
from risk.models import Risk, RiskScenario


class RiskScenarioHtmxView(LoginRequiredMixin, ListView, FormView):
    """
    View for displaying a table of Risk Scenario and handle creation of Risk.

    Permission "risk.change_risk"
        - POST to create new risk
    """

    template_name = "risk/htmx/risk_scenario_htmx.html"
    model = RiskScenario
    form_class = RiskForm
    success_url = reverse_lazy("risk:risk_scenario")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def post(self, request, *args, **kwargs):
        if self.request.user.has_perm("risk.change_risk"):
            return super().post(request, *args, **kwargs)
        else:
            return self.handle_no_permission()

    def form_valid(self, form):
        risk_scenario_object = get_object_or_404(
            RiskScenario, pk=self.request.POST.get("scenario")
        )
        if Risk.objects.filter(
            scenario=risk_scenario_object, project=form.cleaned_data["project"]
        ).exists():
            messages.error(
                self.request,
                f"{risk_scenario_object.name} already exists for {form.cleaned_data['project']}",
                extra_tags="danger",
            )
            return HttpResponseRedirect(self.get_success_url())

        new_risk = form.save(commit=False)
        new_risk.scenario = risk_scenario_object
        new_risk.status = "not_mitigated"
        new_risk.save()
        messages.info(
            self.request,
            f"{risk_scenario_object.name} created successfully for {form.cleaned_data['project']}",
        )

        return HttpResponseRedirect(self.get_success_url())

risk/views/risk_table_htmx_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from risk.models import Project


class RiskTableHtmxView(LoginRequiredMixin, ListView):
    """
    View for displaying a table of Project summaries

    Permission "risk.view_project"
        - View all projects
    w/o Permission "risk.view_project"
        - View only projects owned by user
    """

    template_name = "risk/htmx/risk_table_htmx.html"
    queryset = Project.objects.get_summary()

    def get_queryset(self, **kwargs):
        if not self.request.user.has_perm("risk.view_project"):
            self.queryset = self.queryset.filter(owner=self.request.user)

        return super().get_queryset(**kwargs)

risk/templates/loading_card.html
{% load static %}
<div class="row">
  <div class="col-3 mb-3"></div>
  <div class="col-6 mb-3">
    <div class="card h-100 mx-auto">
      <img class="card-img-top" src="{% static 'img/backgrounds/loading-animation-dashboard.gif' %}" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Loading....</h5>
      </div>
    </div>
  </div>
  <div class="col-3 mb-3"></div>
</div>

risk/templates/navbar.html
{% load static %}
<nav
  class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
  id="layout-navbar">
  <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
    <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
      <i class="bx bx-menu bx-sm"></i>
    </a>
  </div>

  <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
    <ul class="navbar-nav flex-row align-items-center ms-auto">
      <!-- User -->
      <li class="nav-item navbar-dropdown dropdown-user dropdown">
        <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
          <div class="avatar avatar-online">
            <img src="{% static 'img/avatars/person-circle-outline.svg' %}" alt class="w-px-40 h-auto rounded-circle" />
          </div>
        </a>
        <ul class="dropdown-menu dropdown-menu-end">
          <li>
            <a class="dropdown-item" href="javascript:void(0);">
              <div class="d-flex">
                <div class="flex-shrink-0 me-3">
                  <div class="avatar avatar-online">
                    <img src="{% static 'img/avatars/person-circle-outline.svg' %}" alt class="w-px-40 h-auto rounded-circle" />
                  </div>
                </div>
                <div class="flex-grow-1">
                  <span class="fw-medium d-block">{{ request.user.username }}</span>
                  <small class="text-muted">{{ request.user.groups.all.first }}</small>
                </div>
              </div>
            </a>
          </li>
          <li>
            <div class="dropdown-divider"></div>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'logout' %}">
              <i class="bx bx-power-off me-2"></i>
              <span class="align-middle">Log Out</span>
            </a>
          </li>
        </ul>
      </li>
      <!--/ User -->
    </ul>
  </div>
</nav>

risk/templates/sidebar.html
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
  <div class="app-brand demo">
    <a href="/" class="app-brand-link">
      <span class="app-brand-text demo menu-text fw-bold ms-2">risk m8t</span>
    </a>
    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
      <i class="bx bx-chevron-left bx-sm align-middle"></i>
    </a>
  </div>

  <div class="menu-inner-shadow"></div>

  <ul class="menu-inner py-1">
    <!-- Apps -->
    <li class="menu-item {% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}">
      <a
        href="{% url 'risk:dashboard' %}"
        class="menu-link">
        <i class="menu-icon tf-icons bx bx-home-circle"></i>
        <div data-i18n="Dashboard">Dashboard</div>
      </a>
    </li>
    <li class="menu-item {% if request.resolver_match.url_name == 'risk_scenario' %}active{% endif %}">
      <a
        href="{% url 'risk:risk_scenario' %}"
        class="menu-link">
        <i class="menu-icon tf-icons bx bx-analyse"></i>
        <div data-i18n="Risk Scenario">Risk Scenario</div>
      </a>
    </li>
    <li class="menu-item {% if request.resolver_match.url_name == 'risk_table' %}active{% endif %}">
      <a
        href="{% url 'risk:risk_table' %}"
        class="menu-link">
        <i class="menu-icon tf-icons bx bx-table"></i>
        <div data-i18n="Risk Table">Risk Table</div>
      </a>
    </li>
  </ul>
</aside>